language: python
python:
  - "3.6"
  - "3.5"
script: nosetests
env:
  - DJANGO=2.0.4
install: # => 5
    - pip install -r requirements.txt
before_install:
  pip install codecov
after_success:
  codecov

