language: python
python:
  - "3.6"
  - "3.5"
script: nosetests

env:
  - DJANGO_VERSION=2.0.4
  
install:
  - pip install -q Django==$DJANGO_VERSION
  - python setup.py -q install

before_install:
  pip install codecov
after_success:
  codecov

